// Data URI for a basic PNG logo as fallback
const LOGO_PNG_DATA_URI = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAyAAAAYAGCAYAAABAP/8AAAE1hZAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZQJpY2Vf+GGCj5MFK5Ij5BgAAAABJRU5ErkJggg==";

export { LOGO_PNG_DATA_URI };
